name: Build Zig Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build x86_64 release
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-musl -Dstrip=true
          mv zig-out/bin/zelky zig-out/bin/zelky-x86_64-linux-musl

      - name: Build aarch64 release
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=aarch64-linux-musl -Dstrip=true
          mv zig-out/bin/zelky zig-out/bin/zelky-aarch64-linux-musl

      - name: Build Windows x86_64 release
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=x86_64-windows-gnu -Dstrip=true
          mv zig-out/bin/zelky.exe zig-out/bin/zelky-x86_64-windows-gnu.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: zig-out/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
